### ISSUE TITLE
installation problems - package inconsistencies et al

### ISSUE THREAD

**Issue by rtalasilawfb** [KrishnaswamyLab/ReLSO-Guided-Generative-Protein-Design-using-Regularized-Transformers#3]
Hi,

Thank you for putting together the code on github.

However I encountered some installation problems. Here are a couple:

1) There are inconsistencies in the package requirements. The relso_env.yml file needs to be edited as the packages with specific labels are not available on conda. For example: "python=3.10.4=hdfd78df_0".
2) the torch version in relso_env.yml specifies 1.12.0, but the requirements.txt requires "torch=1.7.1". 
3) The "pip install -e ." gives an error " error: Multiple top-level packages discovered in a flat-layout: ['data', 'relso']."

I am trying the install on a fresh computing instance on GCP (4x T4 GPU, 30 GB RAM, 500 GB disk). Wanted to check if the installation & setup was successfully completed on a clean machine before.

**Comment by luis-sribeiro** [comment]
> Hi,
> 
> Thank you for putting together the code on github.
> 
> However I encountered some installation problems. Here are a couple:
> 
> 1. There are inconsistencies in the package requirements. The relso_env.yml file needs to be edited as the packages with specific labels are not available on conda. For example: "python=3.10.4=hdfd78df_0".
> 2. the torch version in relso_env.yml specifies 1.12.0, but the requirements.txt requires "torch=1.7.1".
> 3. The "pip install -e ." gives an error " error: Multiple top-level packages discovered in a flat-layout: ['data', 'relso']."
> 
> I am trying the install on a fresh computing instance on GCP (4x T4 GPU, 30 GB RAM, 500 GB disk). Wanted to check if the installation & setup was successfully completed on a clean machine before.

Hi, were you able to install it?

**Comment by rtalasilawfb** [comment]
Nope. I couldn’t install it.

**Comment by ec1340** [comment]
Hi thanks for raising this issue and for your patience!

Hopefully this issue is addressed with the latest merge #4 . The updated installation instructions can be found in the `README.md`. 

Reposted here, 

```
# make conda environment
conda create --name relsoenv python=3.9
conda activate relsoenv

# install pytorch
# GPU (linux)
pip3 install torch torchvision torchaudio

# CPU only (linux)
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# CPU only (mac)
pip3 install torch torchvision torchaudio

# install other dependencies
python -m pip install networkx pytorch-lightning==1.9 wandb scikit-learn pandas matplotlib gdown phate

# install relso
pip install -e .   
```

**Comment by rtalasilawfb** [comment]
The install went ahead without a problem this time. 

There is a small missing step before step 4 in the install instructions. Before doing ‘pip install -e .’, one needs to do ‘cd ReLSO-Guided-Generative-Protein-Design-using-Regularized-Transformers’. This is not a big issue as folks can easily figure out the need to position in the correct directory before running pip.

However I found the below problems while doing the training on GPU:

"python train_relso.py --data gifford —n_gpus=4” gave the following error

File "/home/ubuntu/miniconda3/envs/relsoenv/lib/python3.9/site-packages/torch/nn/functional.py", line 2416, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64])

I then tried running on CPU and I got the following error:

training complete!

now beginning evaluations...

train sequences raw shape: torch.Size([57603, 20])
valid sequences raw shape: torch.Size([10166, 20])
test sequences raw shape: torch.Size([22690, 20])
——
—

model has fitness predictions
shape of train outputs:
torch.Size([57603, 22, 20]), torch.Size([57603, 1])
Traceback (most recent call last):
  File "/home/ubuntu/data/ReLSO-Guided-Generative-Protein-Design-using-Regularized-Transformers/train_relso.py", line 268, in <module>
    seqd_list = [data.train_split_seqd, data.valid_split_seqd, data.test_split_seqd]
AttributeError: 'EnsGradData' object has no attribute 'train_split_seqd'(base)
